# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FineFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_file', models.FileField(upload_to=b'')),
            ],
        ),
    ]
