# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FineFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('fine_file', models.FileField(upload_to=myapp.models.file_using_key_path)),
            ],
        ),
    ]
